# News Category Hackathon Solution

In [17]:
import pandas as pd

In [18]:
train_data = pd.read_excel("Data_Train.xlsx")

## Exploring Data

In [19]:
train_data.head(10)

                                               STORY  SECTION
0  But the most painful was the huge reversal in ...        3
1  How formidable is the opposition alliance amon...        0
2  Most Asian currencies were trading lower today...        3
3  If you want to answer any question, click on ‘...        1
4  In global markets, gold prices edged up today ...        3
5  BEIJING: Chinese tech giant Huawei has announc...        1
6  Mumbai: India Inc's external commercial borrow...        3
7  On Wednesday, Federal Reserve Chairman Jerome ...        3
8  What more can you give to the audience? I have...        2
9  com, Arbaaz Khan spoke about getting back to D...        2

In [20]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7628 entries, 0 to 7627
Data columns (total 2 columns):
STORY      7628 non-null object
SECTION    7628 non-null int64
dtypes: int64(1), object(1)
memory usage: 119.3+ KB

In [21]:
train_data.SECTION = train_data.SECTION.astype('str')

In [22]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7628 entries, 0 to 7627
Data columns (total 2 columns):
STORY      7628 non-null object
SECTION    7628 non-null object
dtypes: object(2)
memory usage: 119.3+ KB

In [25]:
train_data.describe()

                                                    STORY SECTION
count                                                7628    7628
unique                                               7548       4
top     This story has been published from a wire agen...       1
freq                                                   28    2772

In [27]:
train_data.drop_duplicates(inplace = True)

In [34]:
train_data.shape

(7551, 2)

In [36]:
train_data.groupby("SECTION").describe()

        STORY
        count unique                                                top freq
SECTION
0        1673   1673  Residents of Bhopal say industrial growth and ...    1
1        2731   2731  Amazon Echo integration is also present in Aud...    1
2        1914   1914  The 37-year-old actor said working on the thre...    1
3        1233   1233  Demand for shorter-maturity bonds is also high...    1

## Data Preprocessing

In [32]:
import nltk

In [51]:
from nltk.corpus import stopwords
import string

In [266]:
#stopwords.words('english')

In [110]:
all_punctuations = string.punctuation + '‘’,:”][],'

In [111]:
def punc_remover(raw_text):
    no_punct = "".join([i for i in raw_text if i not in all_punctuations])
    return no_punct

In [145]:
def stopword_remover(no_punc_text):
    words = no_punc_text.split()
    no_stp_words = " ".join([i for i in words if i not in stopwords.words('english')])
    
    return no_stp_words

In [163]:
lemmer = nltk.stem.WordNetLemmatizer()
def lem(words):
    return " ".join([lemmer.lemmatize(word,'v') for word in words.split()])

In [164]:
def text_cleaner(raw):
    cleaned_text = stopword_remover(punc_remover(raw))
    return lem(cleaned_text)

In [114]:
#text_cleaner("Hi! I am Amal. If you dont know about me. Look me up on LinkedIn")

In [267]:
#train_data['STORY'].head(5).apply(text_cleaner).values

In [167]:
train_data['CLEAN_STORY'] = train_data['STORY'].apply(text_cleaner)

In [268]:
#train_data.values

## Count Vectorizing

In [170]:
from sklearn.feature_extraction.text import CountVectorizer

In [195]:
bow_dictionary = CountVectorizer().fit(train_data['CLEAN_STORY'])

In [196]:
len(bow_dictionary.vocabulary_)

35189

In [197]:
bow_dictionary.vocabulary_

{'but': 7721,
 'painful': 23789,
 'huge': 16266,
 'reversal': 27207,
 'fee': 13456,
 'income': 16799,
 'unheard': 32978,
 'among': 4877,
 'private': 25482,
 'sector': 28421,
 'lenders': 19378,
 'essentially': 12752,
 'mean': 20746,
 'yes': 34967,
 'bank': 6228,
 'take': 31197,
 'grant': 15054,
 'structure': 30581,
 'loan': 19661,
 'deal': 10502,
 'pay': 24168,
 'account': 3976,
 'upfront': 33210,
 'book': 7230,
 'as': 5517,
 'borrowers': 7271,
 'turn': 32567,
 'defaulters': 10634,
 'tie': 31924,
 'fell': 13474,
 'crack': 9905,
 'gill': 14729,
 'vow': 34028,
 'shift': 28928,
 'safer': 27802,
 'practice': 25141,
 'amortize': 4884,
 'rather': 26406,
 'gills': 14734,
 'move': 21696,
 'mend': 20897,
 'past': 24070,
 'ways': 34275,
 'nasty': 22199,
 'surprise': 30965,
 'future': 14308,
 'this': 31792,
 'good': 14910,
 'news': 22490,
 'consider': 9493,
 'investors': 17459,
 'love': 19826,
 'clean': 8820,
 'image': 16601,
 'loathe': 19665,
 'uncertainties': 32829,
 'gain': 14392,
 'without': 34626,
 'pain': 23788,
 'promise': 25627,
 'strong': 30571,
 'stable': 30191,
 'balance': 6134,
 'sheet': 28887,
 'come': 9129,
 'sacrifice': 27774,
 'well': 34373,
 'give': 14760,
 'hop': 16137,
 'phenomenal': 24469,
 'growth': 15174,
 'make': 20218,
 'kapoor': 18362,
 'how': 16218,
 'formidable': 14002,
 'opposition': 23393,
 'alliance': 4670,
 'congress': 9439,
 'jharkhand': 17961,
 'mukti': 21807,
 'morcha': 21591,
 'jmm': 18015,
 'vikas': 33795,
 'prajatantrik': 25162,
 'most': 21624,
 'asian': 5561,
 'currencies': 10158,
 'trade': 32222,
 'lower': 19847,
 'today': 32036,
 'south': 29847,
 'korean': 18861,
 '04': 97,
 'china': 8547,
 'renminbi': 26937,
 '023': 70,
 'offshore': 23171,
 '015': 50,
 'malaysian': 20244,
 'ringgit': 27341,
 '012': 43,
 'indonesian': 16943,
 'rupiah': 27687,
 '011': 41,
 'taiwan': 31192,
 'dollar': 11625,
 '006': 22,
 'however': 16221,
 'japanese': 17820,
 'yen': 34962,
 '032': 88,
 'the': 31684,
 'index': 16849,
 'measure': 20755,
 'us': 33284,
 'currencys': 10161,
 'strength': 30541,
 'major': 20209,
 '9726': 3676,
 '014': 49,
 'previous': 25388,
 'close': 8889,
 '97395': 3679,
 'if': 16516,
 'want': 34148,
 'answer': 5084,
 'question': 26028,
 'click': 8850,
 'after': 4316,
 'also': 4730,
 'check': 8442,
 'reply': 26978,
 'users': 33327,
 'proceed': 25525,
 'either': 12223,
 'write': 34772,
 'voice': 33967,
 'command': 9153,
 'ask': 5570,
 'few': 13522,
 'prefix': 25274,
 'already': 4727,
 'insert': 17158,
 'help': 15778,
 'submit': 30664,
 'app': 5249,
 'send': 28579,
 'neighbour': 22384,
 'let': 19417,
 'know': 18779,
 'many': 20430,
 'done': 11650,
 'you': 35014,
 'bell': 6561,
 'icon': 16456,
 'homepage': 16087,
 'follow': 13902,
 'in': 16729,
 'global': 14802,
 'market': 20488,
 'gold': 14886,
 'price': 25391,
 'edge': 12137,
 'disappoint': 11303,
 'chinese': 8556,
 'factory': 13222,
 'activity': 4066,
 'data': 10404,
 'bring': 7468,
 'back': 5996,
 'concern': 9358,
 'health': 15671,
 'economy': 12117,
 'dent': 10822,
 'risk': 27365,
 'appetite': 5267,
 'spot': 30086,
 'rise': 27356,
 '1285': 503,
 'per': 24307,
 'ounce': 23528,
 'european': 12816,
 'equity': 12675,
 'nudge': 22956,
 'weaker': 34283,
 'stock': 30440,
 'beijing': 6542,
 'tech': 31370,
 'giant': 14707,
 'huawei': 16249,
 'announce': 5047,
 'plan': 24696,
 'release': 26855,
 'nextgeneration': 22513,
 'smartphone': 29538,
 'base': 6338,
 'technology': 31400,
 'instead': 17205,
 'components': 9307,
 'step': 30378,
 'efforts': 12192,
 'compete': 9257,
 'directly': 11274,
 'western': 34418,
 'industry': 16976,
 'leaders': 19270,
 'thursdays': 31906,
 'announcement': 5050,
 'technologies': 31398,
 'ltd': 19894,
 'worlds': 34724,
 'biggest': 6850,
 'maker': 20222,
 'network': 22442,
 'gear': 14561,
 'phone': 24503,
 'company': 9225,
 'combat': 9118,
 'warn': 34179,
 'might': 21113,
 'security': 28440,
 'mumbai': 21879,
 'india': 16855,
 'incs': 16825,
 'external': 13088,
 'commercial': 9170,
 'borrow': 7270,
 'ecbs': 12094,
 '45': 2278,
 '242': 1445,
 'billion': 6893,
 'january': 17812,
 '2019': 1203,
 'compare': 9230,
 'yearago': 34934,
 'period': 24342,
 'reserve': 27047,
 'rbi': 26471,
 'show': 29046,
 'domestic': 11637,
 'firm': 13676,
 'raise': 26188,
 '540': 2537,
 'overseas': 23662,
 'source': 29845,
 '2018': 1193,
 'of': 23120,
 'total': 32155,
 'month': 21561,
 '227': 1377,
 'automatic': 5842,
 'route': 27567,
 'remain': 26891,
 '150': 731,
 'million': 21164,
 'approval': 5320,
 'accord': 3970,
 'ecb': 12093,
 'on': 23250,
 'wednesday': 34336,
 'federal': 13450,
 'chairman': 8254,
 'jerome': 17918,
 'powell': 25101,
 'say': 28162,
 'interest': 17309,
 'rat': 26393,
 'could': 9805,
 'hold': 16046,
 'some': 29742,
 'time': 31953,
 'weigh': 34355,
 'economic': 12110,
 'outlook': 23569,
 'inflation': 17033,
 'mute': 21963,
 '10year': 304,
 'gild': 14727,
 'yield': 34984,
 '7328': 3176,
 'wednesdays': 34337,
 '7361': 3195,
 'bond': 7210,
 'opposite': 23392,
 'directions': 11272,
 'what': 34435,
 'audience': 5757,
 'do': 11583,
 'yeh': 34958,
 'hai': 15334,
 'aashiqui': 3816,
 'pyaar': 25947,
 'tune': 32545,
 'kya': 18994,
 'kiya': 18753,
 'always': 4758,
 'think': 31761,
 'two': 32627,
 'kind': 18698,
 'people': 24299,
 'bad': 6047,
 'keep': 18526,
 'interchange': 17303,
 'situations': 29360,
 'com': 9110,
 'arbaaz': 5368,
 'khan': 18607,
 'speak': 29913,
 'get': 14662,
 'dabangg': 10265,
 'salman': 27899,
 'perfectly': 24323,
 'slip': 29477,
 'character': 8349,
 'seven': 28709,
 'years': 34946,
 'shoot': 28987,
 'song': 29765,
 'indore': 16948,
 'saw': 28154,
 'brother': 7522,
 'set': 28679,
 'one': 23259,
 'would': 34750,
 'development': 10995,
 'test': 31595,
 'process': 25527,
 'wouldve': 34752,
 'uncover': 32855,
 'flaw': 13778,
 'yet': 34974,
 'put': 25929,
 'anyway': 5205,
 'bryan': 7555,
 'ma': 19987,
 'vice': 33703,
 'president': 25355,
 'devices': 11013,
 'research': 27035,
 'consultancy': 9547,
 'idc': 16466,
 'clearly': 8836,
 'cant': 7906,
 'afford': 4296,
 'another': 5077,
 'embarrass': 12347,
 'note': 22857,
 '7like': 3352,
 'incident': 16778,
 'lest': 19416,
 'build': 7620,
 'reputation': 27017,
 'unreliable': 33110,
 'products': 25559,
 'episode': 12646,
 'trigger': 32402,
 'recall': 26576,
 'cost': 9783,
 'billions': 6899,
 'dollars': 11629,
 'mar': 20439,
 'battle': 6391,
 'apple': 5273,
 'inc': 16753,
 'premium': 25303,
 'pulling': 25830,
 'fold': 13887,
 'address': 4125,
 'potential': 25082,
 'issue': 17610,
 'race': 26102,
 'flexible': 13791,
 'gadget': 14373,
 'ahead': 4413,
 'rival': 27385,
 'co': 8938,
 'xiaomi': 34840,
 'corp': 9739,
 'samsung': 27956,
 'spokeswoman': 30062,
 'decline': 10588,
 'comment': 9162,
 'story': 30481,
 'shares': 28842,
 'hasnt': 15563,
 'date': 10435,
 'launch': 19200,
 'little': 19616,
 'change': 8325,
 'seoul': 28627,
 'bounce': 7298,
 'since': 29265,
 'largest': 19141,
 'producer': 25548,
 'smartphones': 29546,
 'memory': 20892,
 'chip': 8563,
 'count': 9812,
 'extend': 13078,
 'lead': 19266,
 'mobile': 21389,
 'kickstart': 18669,
 'stagnate': 30203,
 'unveiled': 33165,
 'along': 4715,
 '10thanniversary': 299,
 'version': 33662,
 'flagship': 13751,
 'galaxy': 14411,
 'underscore': 32905,
 'samsungs': 27959,
 'ambition': 4824,
 'like': 19504,
 'product': 25550,
 'struggling': 30586,
 'ward': 34159,
 'hardcharging': 15474,
 'suwon': 31021,
 'koreabased': 18860,
 'embody': 12359,
 'cuttingedge': 10213,
 'innovation': 17131,
 'so': 29657,
 'far': 13306,
 'year': 34932,
 'rupee': 27679,
 '07': 138,
 'foreign': 13962,
 'buy': 7733,
 '843': 3445,
 '106': 242,
 'debt': 10541,
 'indias': 16894,
 'benchmark': 6581,
 'sensex': 28602,
 '022': 69,
 '38667': 2049,
 'point': 24854,
 'preopen': 25313,
 'see': 28449,
 'presence': 25338,
 'jio': 17993,
 'rural': 27688,
 'enabler': 12442,
 'eventually': 12848,
 'expect': 12995,
 'upgrade': 33211,
 'local': 19670,
 'entrepreneurs': 12616,
 'apply': 5301,
 'open': 23352,
 'xiaomis': 34848,
 'mi': 21007,
 'stores': 30469,
 'responsible': 27104,
 'physical': 24557,
 'infrastructure': 17065,
 'real': 26502,
 'estate': 12758,
 'look': 19775,
 'brand': 7369,
 'store': 30465,
 'detail': 10948,
 'ad': 4092,
 'read': 26492,
 'no': 22656,
 'whistle': 34474,
 'bezel': 6696,
 'notch': 22855,
 'lag': 19040,
 'bloatware': 7080,
 '2000': 1135,
 'tag': 31178,
 'random': 26341,
 'music': 21937,
 'just': 18175,
 'better': 6671,
 'contain': 9570,
 'sketch': 29394,
 'triple': 32422,
 'camera': 7839,
 'setup': 28705,
 'popup': 24989,
 'front': 14207,
 'face': 13177,
 'mechanism': 20766,
 'seem': 28458,
 'copper': 9716,
 'heat': 15705,
 'pipe': 24641,
 'cool': 9690,
 'sim': 29221,
 'card': 7965,
 'slot': 29488,
 'bottom': 7293,
 'leave': 19314,
 'side': 29156,
 'design': 10903,
 'line': 19541,
 'case': 8037,
 'render': 26929,
 'wired': 34597,
 'magazine': 20083,
 'even': 12838,
 'hand': 15397,
 'productionready': 25553,
 'prototype': 25720,
 'oneplus': 23283,
 'pro': 25504,
 'post': 25040,
 'sample': 27953,
 'device': 11010,
 'azerbaijan': 5950,
 'grand': 15039,
 'prix': 25493,
 'baku': 6122,
 'tuesday': 32522,
 'healthy': 15676,
 'crosscurrents': 10023,
 'conflict': 9415,
 'signal': 29183,
 'officials': 23159,
 'decide': 10574,
 'warrant': 34184,
 'patient': 24113,
 'approach': 5315,
 'interestrate': 17313,
 'public': 25795,
 'higher': 15879,
 'remove': 26922,
 'allahabad': 4650,
 'corporation': 9744,
 'dhanlaxmi': 11059,
 'prompt': 25642,
 'corrective': 9752,
 'action': 4043,
 'pca': 24190,
 'framework': 14099,
 'subject': 30654,
 'certain': 8219,
 'condition': 9377,
 'continuous': 9609,
 'monitor': 21537,
 '10': 167,
 'feature': 13425,
 'display': 11436,
 'responsive': 27106,
 'inturn': 17427,
 'significantly': 29190,
 'game': 14436,
 'ui': 32731,
 'experience': 13012,
 'it': 17623,
 'consume': 9554,
 'battery': 6385,
 'toggle': 32049,
 'switch': 31084,
 'within': 34625,
 'settings': 28694,
 'much': 21765,
 'present': 25340,
 'asus': 5665,
 'rog': 27455,
 'razer': 26464,
 'tiktok': 31945,
 'popular': 24977,
 'children': 8535,
 'criticism': 10003,
 'different': 11163,
 'quarter': 26008,
 'circulation': 8737,
 'pornographic': 24996,
 'content': 9585,
 'any': 5193,
 'exist': 12971,
 'user': 33317,
 'instal': 17192,
 'share': 28829,
 'seeker': 28454,
 'apps': 5327,
 'shareit': 28840,
 'new': 22467,
 'delhi': 10705,
 'with': 34617,
 'crores': 10018,
 'use': 33305,
 'option': 23419,
 'others': 23522,
 'block': 7083,
 'access': 3946,
 'google': 14928,
 'play': 24735,
 'may': 20677,
 'desire': 10914,
 'result': 27128,
 'experts': 13021,
 'download': 11734,
 'short': 29003,
 'videosharing': 33734,
 'request': 27020,
 'government': 14983,
 'hive': 16015,
 'business': 7703,
 'whollyowned': 34493,
 'subsidiary': 30690,
 'slump': 29509,
 'sale': 27864,
 'abide': 3868,
 'rule': 27653,
 'capital': 7926,
 'regulator': 26790,
 'securities': 28438,
 'exchange': 12920,
 'board': 7147,
 'sebi': 28385,
 'crisil': 9985,
 'press': 25363,
 'notwithstanding': 22894,
 'begin': 6507,
 'reflect': 26727,
 'businesss': 7712,
 'drag': 11769,
 'overall': 23614,
 'earn': 12036,
 'hiveoff': 16016,
 'likely': 19509,
 'continue': 9605,
 'driver': 11825,
 'valuation': 33458,
 '28': 1628,
 'oneyear': 23307,
 'forward': 14032,
 'he': 15637,
 'choose': 8611,
 'hide': 15861,
 'cp': 9891,
 'colleagues': 9054,
 'mother': 21637,
 'house': 16205,
 'form': 13986,
 'sexual': 28738,
 'relations': 26843,
 'first': 13688,
 'three': 31830,
 'episodes': 12647,
 'oh': 23183,
 'hes': 15837,
 'right': 27314,
 'dare': 10367,
 'find': 13638,
 'happiness': 15447,
 'offer': 23131,
 'explanation': 13028,
 'phil': 24475,
 'soldier': 29713,
 'ass': 5588,
 'special': 29926,
 'pack': 23747,
 'pop': 24974,
 'culture': 10127,
 'reference': 26713,
 'gone': 14906,
 'girl': 14754,
 'mindy': 21195,
 'kaling': 18282,
 'thats': 31680,
 'opera': 23362,
 'simply': 29252,
 'go': 14842,
 'try': 32495,
 'aim': 4448,
 'ipad': 17487,
 'specific': 29943,
 'type': 32669,
 'artists': 5501,
 'aware': 5919,
 'fact': 13209,
 'sales': 27882,
 'ship': 28945,
 'sail': 27833,
 'promote': 25634,
 'highend': 15877,
 'ideal': 16469,
 'photographers': 24537,
 'creators': 9943,
 'its': 17650,
 'perfect': 24321,
 'eagerly': 12020,
 'wait': 34096,
 'refresh': 26740,
 'last': 19156,
 'update': 33192,
 'nearly': 22324,
 '17': 876,
 'months': 21564,
 'ago': 4379,
 'anticipate': 5112,
 'though': 31816,
 'drastically': 11790,
 'increase': 16818,
 'iphones': 17504,
 'iphone': 17497,
 'high': 15864,
 'manage': 20294,
 'revenue': 27199,
 'for': 13937,
 'plus': 24804,
 '72000': 3141,
 'xs': 34872,
 'start': 30280,
 '99999': 3716,
 'facebook': 13178,
 'eligible': 12305,
 'able': 3871,
 'money': 21522,
 'videos': 33733,
 'breaks': 7412,
 'photo': 24532,
 'afp': 4306,
 'watch': 34217,
 'video': 33725,
 'youtube': 35043,
 'internationally': 17343,
 'expand': 12985,
 'financial': 13630,
 'incentives': 16764,
 'encourage': 12453,
 'facebookfacebook': 13181,
 'watchfacebook': 34228,
 'serviceyoutubefidji': 28675,
 'simoentertainmentsports': 29241,
 'contenttechnology': 9588,
 'starring': 30266,
 'varun': 33525,
 'dhawan': 11079,
 'alia': 4618,
 'bhatt': 6775,
 'sonakshi': 29756,
 'sinha': 29312,
 'aditya': 4148,
 'roy': 27579,
 'kapur': 18367,
 'madhuri': 20062,
 'dixit': 11558,
 'sanjay': 28011,
 'dutt': 11981,
 'kalank': 18264,
 'makers': 20223,
 'weekend': 34342,
 'competition': 9263,
 'sight': 29178,
 'film': 13585,
 'splendid': 30045,
 'box': 7322,
 'office': 23150,
 'tweet': 32604,
 'bang': 6208,
 'emerges': 12378,
 'opener': 23353,
 'plexes': 24774,
 'terrific': 31572,
 'impressive': 16700,
 'cast': 8060,
 'hype': 16383,
 'massive': 20584,
 'screen': 28296,
 '4000': 2143,
 'mahavirjayanti': 20148,
 'holiday': 16058,
 'contribute': 9627,
 'big': 6846,
 'wed': 34330,
 '21': 1285,
 'gkn': 14768,
 'bar': 6261,
 'misuse': 21333,
 'socalled': 29665,
 'dark': 10373,
 'fibre': 13536,
 'appeal': 5258,
 'separate': 28629,
 'order': 23445,
 'nse': 22939,
 'six': 29369,
 'disgorge': 11383,
 '1200': 430,
 'profit': 25575,
 'colocation': 9083,
 'service': 28670,
 '2010': 1167,
 '2014': 1178,
 'include': 16791,
 'fintech': 13661,
 'startup': 30287,
 'zeta': 35129,
 'cofounded': 9002,
 'bhavin': 6784,
 'turakhia': 32552,
 'ramki': 26307,
 'gaddipati': 14371,
 'digitise': 11200,
 'employee': 12423,
 'benefit': 6595,
 'cafeteria': 7790,
 'solutions': 29732,
 'reward': 27249,
 'recognition': 26613,
 'cloudbased': 8905,
 'enterprise': 12583,
 'suite': 30779,
 'call': 7815,
 'tax': 31317,
 'package': 23748,
 'payment': 24177,
 'solution': 29731,
 'publish': 25806,
 'wire': 34596,
 'agency': 4346,
 'modifications': 21439,
 'text': 31611,
 'only': 23319,
 'headline': 15647,
 'globally': 14805,
 'establish': 12755,
 'stratasys': 30512,
 'optomec': 23423,
 'footprints': 13934,
 'partnerships': 24026,
 'alliances': 4672,
 'abovecited': 3883,
 '6wresearch': 3036,
 'active': 4055,
 'indian': 16877,
 '3dprinting': 2110,
 'space': 29864,
 'altem': 4734,
 'imaginarium': 16606,
 'brahma': 7353,
 'kcbots': 18503,
 'jgroup': 17954,
 'robotics': 27430,
 'sit': 29342,
 'disney': 11417,
 'researchs': 27038,
 'magic': 20087,
 'bench': 6580,
 'elephant': 12294,
 'glow': 14828,
 'orb': 23436,
 'or': 23425,
 'tiny': 31990,
 'donkey': 11653,
 'saunter': 28141,
 'kick': 18665,
 'similarly': 29233,
 'scientists': 28255,
 'worcester': 34674,
 'polytechnic': 24938,
 'institute': 17212,
 'microsoft': 21052,
 'hololens': 16073,
 'explore': 13039,
 'complex': 9290,
 'biological': 6924,
 '3d': 2109,
 'create': 9931,
 'tool': 32106,
 'critical': 9999,
 'link': 19557,
 'proteins': 25712,
 'genes': 14606,
 'relate': 26841,
 'disorder': 11421,
 'cancer': 7883,
 'diabetes': 11104,
 'both': 7282,
 'examples': 12900,
 'highlight': 15894,
 'meld': 20859,
 'augment': 5777,
 'reality': 26515,
 'ar': 5356,
 'virtual': 33864,
 'vr': 34036,
 'world': 34718,
 'businesses': 7705,
 'mixed': 21348,
 'mr': 21731,
 'blended': 7058,
 'concept': 9352,
 'while': 34464,
 'solely': 29715,
 'computers': 9340,
 'online': 23315,
 'still': 30425,
 'elements': 12292,
 'atop': 5710,
 'akin': 4537,
 'layer': 19253,
 'information': 17053,
 'mix': 21347,
 'realities': 26514,
 'bid': 6832,
 'capture': 7953,
 'best': 6651,
 'traction': 32218,
 'need': 22345,
 'headsets': 15659,
 'regardless': 26763,
 'believe': 6557,
 'become': 6478,
 'next': 22510,
 'compute': 9336,
 'platform': 24727,
 'leap': 19295,
 'goggle': 14871,
 'ever': 12849,
 'investments': 17457,
 'almost': 4711,
 'notably': 22854,
 'alibaba': 4624,
 'group': 15162,
 'temasek': 31489,
 'jp': 18104,
 'morgan': 21603,
 'investment': 17456,
 'management': 20296,
 'headset': 15658,
 'finally': 13626,
 'creator': 9941,
 'edition': 12153,
 'available': 5864,
 '2295': 1387,
 'other': 23521,
 'players': 24744,
 'intel': 17250,
 'seiko': 28481,
 'epson': 12652,
 'accenture': 3940,
 'plc': 24761,
 'sony': 29782,
 'electronics': 12284,
 'htc': 16241,
 'startups': 30289,
 'imaginate': 16608,
 'increasingly': 16820,
 'bet': 6663,
 'gartner': 14514,
 'predict': 25245,
 'evaluate': 12827,
 'adopt': 4191,
 '20': 1133,
 'largeenterprise': 19133,
 'size': 29381,
 'reach': 26483,
 '2023': 1222,
 'reportbuyercom': 26984,
 'rapid': 26372,
 'demand': 10751,
 'innovative': 17134,
 'wearable': 34297,
 'aerospace': 4266,
 'defence': 10642,
 'sectors': 28424,
 'train': 32250,
 'program': 25585,
 'effectively': 12179,
 'school': 28242,
 'provide': 25732,
 'interactive': 17297,
 'learn': 19297,
 'report': 26983,
 'mintindiawire': 21245,
 'longreads': 19768,
 'technologyfuture': 31404,
 'technologyartificial': 31402,
 'intelligenceblockchaininternet': 17259,
 'things3d': 31757,
 'printingmixed': 25458,
 'realityaugmented': 26518,
 'realityvirtual': 26520,
 'statements': 30313,
 'yeddyurappa': 34954,
 'air': 4459,
 'strike': 30560,
 'bharatiya': 6747,
 'janata': 17788,
 'party': 24032,
 'bjp': 6995,
 'bag': 6077,
 'around': 5461,
 '22': 1350,
 'parliamentary': 23985,
 'seat': 28372,
 'karnataka': 18403,
 'replenish': 26973,
 'pakistans': 23810,
 'arsenal': 5478,
 'attack': 5720,
 'twist': 32620,
 ...}

In [184]:
train_data['CLEAN_STORY'][0]

'But painful huge reversal fee income unheard among private sector lenders Essentially mean Yes Bank take grant fee structure loan deal pay account upfront book As borrowers turn defaulters fee tie loan deal fell crack Gill vow shift safer account practice amortize fee income rather book upfront Gills move mend past ways mean nasty surprise future This good news consider investors love clean image loathe uncertainties But gain without pain promise strong stable balance sheet come sacrifice well Investors give hop phenomenal growth promise make Kapoor'

In [190]:
print(bow.transform([train_data['CLEAN_STORY'][0]]).shape)

(1, 35189)

In [192]:
print(bow.transform([train_data['CLEAN_STORY'][0]]))

  (0, 3976)	2
  (0, 4877)	1
  (0, 4884)	1
  (0, 5517)	1
  (0, 6134)	1
  (0, 6228)	1
  (0, 7230)	2
  (0, 7271)	1
  (0, 7721)	2
  (0, 8820)	1
  (0, 9129)	1
  (0, 9493)	1
  (0, 9905)	1
  (0, 10502)	2
  (0, 10634)	1
  (0, 12752)	1
  (0, 13456)	4
  (0, 13474)	1
  (0, 14308)	1
  (0, 14392)	1
  (0, 14729)	1
  (0, 14734)	1
  (0, 14760)	1
  (0, 14910)	1
  (0, 15054)	1
  :	:
  (0, 25482)	1
  (0, 25627)	2
  (0, 26406)	1
  (0, 27207)	1
  (0, 27774)	1
  (0, 27802)	1
  (0, 28421)	1
  (0, 28887)	1
  (0, 28928)	1
  (0, 30191)	1
  (0, 30571)	1
  (0, 30581)	1
  (0, 30965)	1
  (0, 31197)	1
  (0, 31792)	1
  (0, 31924)	1
  (0, 32567)	1
  (0, 32829)	1
  (0, 32978)	1
  (0, 33210)	2
  (0, 34028)	1
  (0, 34275)	1
  (0, 34373)	1
  (0, 34626)	1
  (0, 34967)	1

In [269]:
#bow_dictionary.get_feature_names()[25627]

In [201]:
bow = bow_dictionary.transform(train_data['CLEAN_STORY'])

In [205]:
print(bow.shape)

(7551, 35189)

In [207]:
bow.nnz

414966

In [211]:
sparsity = bow.nnz/(bow.shape[0] * bow.shape[1])
print(sparsity)

0.0015617126171266116

## TFIDF

In [213]:
from sklearn.feature_extraction.text import TfidfTransformer

In [215]:
tfidf_transformer = TfidfTransformer().fit(bow)

In [221]:
tfidf_transformer.idf_[bow_dictionary.vocabulary_['university']]

5.560119855358315

In [222]:
storytfidf = tfidf_transformer.transform(bow)

In [224]:
from sklearn.naive_bayes import MultinomialNB
classfier = MultinomialNB().fit(storytfidf, train_data['SECTION'])

In [264]:
train_p = classfier.predict(storytfidf)

In [265]:
from sklearn.metrics import classification_report

print(classification_report(train_data['SECTION'],train_p))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1673
           1       0.94      1.00      0.97      2731
           2       1.00      0.94      0.97      1914
           3       0.99      0.94      0.97      1233

   micro avg       0.97      0.97      0.97      7551
   macro avg       0.97      0.96      0.97      7551
weighted avg       0.97      0.97      0.97      7551

In [232]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(train_p,train_data['SECTION'])

In [239]:
cm

array([[1621,    7,   43,    5],
       [  46, 2718,   66,   67],
       [   2,    4, 1805,    0],
       [   4,    2,    0, 1161]])

In [237]:
acc = cm.diagonal().sum()/cm.sum()

In [240]:
acc

0.9674215335717123

## Predicting For Test Set

In [241]:
test_data = pd.read_excel("Data_Test.xlsx")

In [243]:
test_data.head(10)

                                               STORY
0  2019 will see gadgets like gaming smartphones ...
1  It has also unleashed a wave of changes in the...
2  It can be confusing to pick the right smartpho...
3  The mobile application is integrated with a da...
4  We have rounded up some of the gadgets that sh...
5  "Imagine if every message you sent was kept wi...
6  Positioned along the four sides of the Asus RO...
7  In fact, when I applied to USC film school the...
8  As spotted by Android Police, Netflix is testi...
9  Her moves were immaculately choreographed as s...

In [245]:
test_data['CLEAN_STORY'] = test_data['STORY'].apply(text_cleaner)

In [248]:
#test_data.values

In [249]:
from sklearn.pipeline import Pipeline

In [253]:
pipe = Pipeline([
    ('bow', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('classifier', MultinomialNB())
])

In [254]:
pipe.fit(train_data['CLEAN_STORY'], train_data['SECTION'])

Pipeline(memory=None,
     steps=[('bow', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_...f=False, use_idf=True)), ('classifier', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [256]:
test_preds = pipe.predict(test_data['CLEAN_STORY'])

In [270]:
test_preds

array(['1', '2', '1', ..., '1', '0', '1'], dtype='<U1')

In [262]:
pd.DataFrame(test_preds, columns = ['SECTION']).to_excel('News_category_soln1.xlsx', index = False)